### ISSUE TITLE
How can I find the doc for urcap 1.7.0

### ISSUE THREAD

**Issue by itfanr** [UniversalRobots/HelloWorldSwing#1]
Hello everyone,

I can only find the doc for urcap 1.3.0. ( https://plus.universal-robots.com/apidoc/40237/index.html)

But where is the doc for 1.7.0 ?

Thank you.

**Comment by BomMadsen** [comment]
Create a user at UR+ Developer Site to access all docs and the SDK. 
Sign up here: https://www.universal-robots.com/plus/developer/
